version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: development
      POSTGRES_DB: {{ cookiecutter.project_slug }}
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    image: redis

  django:
    build: .
    ports:
      - "8000:8000"
    working_dir: /app
    environment:
      DATABASE_URL: postgres://admin:development@postgres:5432/{{ cookiecutter.project_slug }}
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    links:
      - postgres
      - redis

  nginx:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./deploy/nginx/nginx.dev:/etc/nginx/conf.d/default.conf:ro
    - ./static:/var/www/backend/static:ro
    - ./media:/var/www/backend/media:ro
    links:
      - django
