version: '3'

services:
  postgres:
    image: postgres
    # volumes:
    #   - /var/www/django_setup/db:/var/lib/postgresql/data

  redis:
    image: redis

  django:
    build: .
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - .:/app
    links:
      - postgres
      - redis
